from __future__ import annotations

from collections.abc import Sequence

from app.v3.models import Product, ProductCategory


def _product(
    *,
    sku: str,
    name: str,
    brand: str,
    category: ProductCategory,
    subcategory: str,
    price: int,
    rating: float,
    description: str,
    scene_tags: list[str],
    tags: list[str],
    aliases: list[str],
    features: dict[str, str | int | float | bool | None],
    stock: int,
    low_stock_threshold: int = 5,
) -> Product:
    return Product(
        sku=sku,
        name=name,
        brand=brand,
        category=category,
        subcategory=subcategory,
        price=price,
        rating=rating,
        description=description,
        scene_tags=scene_tags,
        tags=tags,
        aliases=aliases,
        features=features,
        stock=stock,
        low_stock_threshold=low_stock_threshold,
    )


_SEED_CATALOG: tuple[Product, ...] = (
    _product(
        sku="PHN-APL-IP16-128",
        name="Apple iPhone 16",
        brand="Apple",
        category=ProductCategory.phone,
        subcategory="flagship_phone",
        price=5999,
        rating=4.8,
        description="Balanced flagship phone with strong battery life and camera consistency.",
        scene_tags=["commute", "daily", "gift"],
        tags=["phone", "手机", "ios", "拍照", "送礼"],
        aliases=["苹果手机", "iPhone", "Apple phone"],
        features={
            "battery_mah": 3561,
            "camera_score": 92,
            "weight_grams": 170,
            "warranty_years": 1,
            "charging_watts": 27,
            "chip": "A18",
        },
        stock=19,
    ),
    _product(
        sku="PHN-APL-IP16P-256",
        name="Apple iPhone 16 Pro",
        brand="Apple",
        category=ProductCategory.phone,
        subcategory="camera_phone",
        price=7999,
        rating=4.9,
        description="Premium camera-centric phone for demanding users and creators.",
        scene_tags=["travel", "office", "gift"],
        tags=["phone", "手机", "拍照", "高端", "送礼"],
        aliases=["苹果 Pro", "iPhone Pro"],
        features={
            "battery_mah": 3582,
            "camera_score": 96,
            "weight_grams": 199,
            "warranty_years": 1,
            "charging_watts": 27,
            "chip": "A18 Pro",
        },
        stock=11,
    ),
    _product(
        sku="PHN-HUA-P70-256",
        name="Huawei Pura 70",
        brand="Huawei",
        category=ProductCategory.phone,
        subcategory="camera_phone",
        price=5499,
        rating=4.7,
        description="Camera-first flagship with strong portrait and zoom performance.",
        scene_tags=["travel", "daily"],
        tags=["phone", "手机", "拍照", "国产旗舰"],
        aliases=["华为手机", "Pura"],
        features={
            "battery_mah": 4900,
            "camera_score": 95,
            "weight_grams": 207,
            "warranty_years": 1,
            "charging_watts": 66,
            "chip": "Kirin",
        },
        stock=14,
    ),
    _product(
        sku="PHN-XIA-14U-512",
        name="Xiaomi 14 Ultra",
        brand="Xiaomi",
        category=ProductCategory.phone,
        subcategory="camera_phone",
        price=6499,
        rating=4.8,
        description="Imaging flagship with Leica-tuned system and strong charging.",
        scene_tags=["travel", "creator"],
        tags=["phone", "手机", "拍照", "快充"],
        aliases=["小米手机", "14 Ultra"],
        features={
            "battery_mah": 5300,
            "camera_score": 97,
            "weight_grams": 219,
            "warranty_years": 1,
            "charging_watts": 90,
            "chip": "Snapdragon 8 Elite",
        },
        stock=12,
    ),
    _product(
        sku="PHN-VIV-X200-256",
        name="vivo X200",
        brand="vivo",
        category=ProductCategory.phone,
        subcategory="camera_phone",
        price=4299,
        rating=4.7,
        description="Well-rounded camera phone with strong portraits and battery life.",
        scene_tags=["daily", "travel"],
        tags=["phone", "手机", "拍照", "续航"],
        aliases=["vivo 手机"],
        features={
            "battery_mah": 5800,
            "camera_score": 91,
            "weight_grams": 197,
            "warranty_years": 1,
            "charging_watts": 90,
            "chip": "Dimensity 9400",
        },
        stock=17,
    ),
    _product(
        sku="PHN-OPP-FX8-256",
        name="OPPO Find X8",
        brand="OPPO",
        category=ProductCategory.phone,
        subcategory="flagship_phone",
        price=4499,
        rating=4.6,
        description="Slim flagship focused on balance, ergonomics, and reliable battery.",
        scene_tags=["daily", "office"],
        tags=["phone", "手机", "轻薄", "旗舰"],
        aliases=["OPPO 手机"],
        features={
            "battery_mah": 5630,
            "camera_score": 89,
            "weight_grams": 193,
            "warranty_years": 1,
            "charging_watts": 80,
            "chip": "Dimensity 9400",
        },
        stock=10,
    ),
    _product(
        sku="PHN-SAM-S24-256",
        name="Samsung Galaxy S24",
        brand="Samsung",
        category=ProductCategory.phone,
        subcategory="compact_flagship",
        price=5999,
        rating=4.7,
        description="Compact Android flagship with strong display and polished software.",
        scene_tags=["office", "daily"],
        tags=["phone", "手机", "小屏", "旗舰"],
        aliases=["三星手机", "Galaxy"],
        features={
            "battery_mah": 4000,
            "camera_score": 88,
            "weight_grams": 168,
            "warranty_years": 1,
            "charging_watts": 25,
            "chip": "Snapdragon 8 Gen 3",
        },
        stock=13,
    ),
    _product(
        sku="PHN-ONE-13-256",
        name="OnePlus 13",
        brand="OnePlus",
        category=ProductCategory.phone,
        subcategory="performance_phone",
        price=4799,
        rating=4.7,
        description="Performance flagship with fast charging and strong sustained speed.",
        scene_tags=["gaming", "daily"],
        tags=["phone", "手机", "性能", "快充"],
        aliases=["一加手机"],
        features={
            "battery_mah": 6000,
            "camera_score": 86,
            "weight_grams": 210,
            "warranty_years": 1,
            "charging_watts": 100,
            "chip": "Snapdragon 8 Elite",
        },
        stock=18,
    ),
    _product(
        sku="PHN-HON-MG7-256",
        name="Honor Magic 7",
        brand="Honor",
        category=ProductCategory.phone,
        subcategory="flagship_phone",
        price=4699,
        rating=4.6,
        description="Balanced flagship with large battery and comfortable daily ergonomics.",
        scene_tags=["daily", "office"],
        tags=["phone", "手机", "续航", "旗舰"],
        aliases=["荣耀手机"],
        features={
            "battery_mah": 5650,
            "camera_score": 87,
            "weight_grams": 199,
            "warranty_years": 1,
            "charging_watts": 100,
            "chip": "Snapdragon 8 Elite",
        },
        stock=15,
    ),
    _product(
        sku="PHN-GOO-P9-128",
        name="Google Pixel 9",
        brand="Google",
        category=ProductCategory.phone,
        subcategory="camera_phone",
        price=5699,
        rating=4.5,
        description="Pixel phone focused on computational photography and clean software.",
        scene_tags=["travel", "daily"],
        tags=["phone", "手机", "拍照", "安卓原生"],
        aliases=["Pixel 手机"],
        features={
            "battery_mah": 4700,
            "camera_score": 93,
            "weight_grams": 188,
            "warranty_years": 1,
            "charging_watts": 27,
            "chip": "Tensor G4",
        },
        stock=9,
    ),
    _product(
        sku="PHN-RED-K80P-256",
        name="Redmi K80 Pro",
        brand="Redmi",
        category=ProductCategory.phone,
        subcategory="performance_phone",
        price=3699,
        rating=4.6,
        description="Value flagship with strong performance and large battery reserve.",
        scene_tags=["gaming", "daily"],
        tags=["phone", "手机", "性能", "性价比"],
        aliases=["红米手机"],
        features={
            "battery_mah": 6000,
            "camera_score": 82,
            "weight_grams": 212,
            "warranty_years": 1,
            "charging_watts": 120,
            "chip": "Snapdragon 8 Elite",
        },
        stock=16,
    ),
    _product(
        sku="PHN-REA-GT7P-256",
        name="realme GT 7 Pro",
        brand="realme",
        category=ProductCategory.phone,
        subcategory="performance_phone",
        price=3399,
        rating=4.5,
        description="Aggressive value performance phone with huge battery and fast charging.",
        scene_tags=["gaming", "daily"],
        tags=["phone", "手机", "性能", "性价比"],
        aliases=["真我手机"],
        features={
            "battery_mah": 6500,
            "camera_score": 80,
            "weight_grams": 222,
            "warranty_years": 1,
            "charging_watts": 120,
            "chip": "Snapdragon 8 Elite",
        },
        stock=20,
    ),
    _product(
        sku="PHN-NTG-2AP-256",
        name="Nothing Phone (2a) Plus",
        brand="Nothing",
        category=ProductCategory.phone,
        subcategory="design_phone",
        price=2499,
        rating=4.4,
        description="Stylish phone with transparent design for gift and daily use.",
        scene_tags=["gift", "daily"],
        tags=["phone", "手机", "设计感", "颜值"],
        aliases=["Nothing 手机"],
        features={
            "battery_mah": 5000,
            "camera_score": 79,
            "weight_grams": 190,
            "warranty_years": 1,
            "charging_watts": 50,
            "chip": "Dimensity 7350 Pro",
        },
        stock=7,
    ),
    _product(
        sku="PHN-MOT-E50U-256",
        name="Motorola Edge 50 Ultra",
        brand="Motorola",
        category=ProductCategory.phone,
        subcategory="design_phone",
        price=3999,
        rating=4.3,
        description="Curved-screen phone with lightweight design and solid charging speed.",
        scene_tags=["gift", "daily"],
        tags=["phone", "手机", "轻薄", "设计感"],
        aliases=["摩托罗拉手机"],
        features={
            "battery_mah": 4500,
            "camera_score": 84,
            "weight_grams": 197,
            "warranty_years": 1,
            "charging_watts": 125,
            "chip": "Snapdragon 8s Gen 3",
        },
        stock=8,
    ),
    _product(
        sku="PHN-SON-X1VI-256",
        name="Sony Xperia 1 VI",
        brand="Sony",
        category=ProductCategory.phone,
        subcategory="creator_phone",
        price=8999,
        rating=4.5,
        description="Creator-focused phone with pro display controls and camera tuning.",
        scene_tags=["creator", "travel"],
        tags=["phone", "手机", "拍照", "索尼"],
        aliases=["索尼手机", "Xperia"],
        features={
            "battery_mah": 5000,
            "camera_score": 90,
            "weight_grams": 192,
            "warranty_years": 1,
            "charging_watts": 30,
            "chip": "Snapdragon 8 Gen 3",
        },
        stock=6,
    ),
    _product(
        sku="EAR-SON-WH1000XM5",
        name="Sony WH-1000XM5",
        brand="Sony",
        category=ProductCategory.earphones,
        subcategory="noise_cancelling_headphones",
        price=2899,
        rating=4.9,
        description="Flagship commute ANC headphone with balanced sound and long battery.",
        scene_tags=["commute", "office", "travel"],
        tags=["earphones", "耳机", "降噪", "通勤", "头戴式"],
        aliases=["降噪耳机", "索尼 XM5", "Sony XM5"],
        features={
            "battery_hours": 30,
            "noise_cancel_score": 9.7,
            "weight_grams": 250,
            "warranty_years": 1,
        },
        stock=12,
    ),
    _product(
        sku="EAR-BOS-QCUH",
        name="Bose QuietComfort Ultra Headphones",
        brand="Bose",
        category=ProductCategory.earphones,
        subcategory="noise_cancelling_headphones",
        price=2999,
        rating=4.8,
        description="Strong ANC over-ear tuned for noisy commute and office use.",
        scene_tags=["commute", "office", "travel"],
        tags=["earphones", "耳机", "降噪", "通勤", "头戴式"],
        aliases=["Bose QC Ultra", "QuietComfort Ultra"],
        features={
            "battery_hours": 24,
            "noise_cancel_score": 9.8,
            "weight_grams": 253,
            "warranty_years": 1,
        },
        stock=9,
    ),
    _product(
        sku="EAR-SEN-M4W",
        name="Sennheiser Momentum 4 Wireless",
        brand="Sennheiser",
        category=ProductCategory.earphones,
        subcategory="noise_cancelling_headphones",
        price=2599,
        rating=4.8,
        description="Travel-friendly over-ear with standout battery life and rich sound.",
        scene_tags=["commute", "travel", "office"],
        tags=["earphones", "耳机", "降噪", "通勤", "头戴式"],
        aliases=["Momentum 4", "森海塞尔木馒头 4"],
        features={
            "battery_hours": 60,
            "noise_cancel_score": 9.2,
            "weight_grams": 293,
            "warranty_years": 2,
        },
        stock=7,
    ),
    _product(
        sku="EAR-APL-APMAX",
        name="Apple AirPods Max",
        brand="Apple",
        category=ProductCategory.earphones,
        subcategory="noise_cancelling_headphones",
        price=3499,
        rating=4.6,
        description="Apple over-ear ANC headphone with excellent ecosystem convenience.",
        scene_tags=["commute", "office", "gift"],
        tags=["earphones", "耳机", "降噪", "苹果生态", "头戴式"],
        aliases=["AirPods Max", "苹果头戴耳机"],
        features={
            "battery_hours": 20,
            "noise_cancel_score": 9.1,
            "weight_grams": 385,
            "warranty_years": 1,
        },
        stock=6,
    ),
    _product(
        sku="EAR-SON-WF1000XM5",
        name="Sony WF-1000XM5",
        brand="Sony",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=1799,
        rating=4.7,
        description="Compact ANC earbuds with strong noise control for commute.",
        scene_tags=["commute", "gym", "daily"],
        tags=["earphones", "耳机", "降噪", "真无线", "通勤"],
        aliases=["Sony WF XM5"],
        features={
            "battery_hours": 24,
            "noise_cancel_score": 9.3,
            "weight_grams": 39,
            "warranty_years": 1,
        },
        stock=13,
    ),
    _product(
        sku="EAR-APL-APPRO2",
        name="Apple AirPods Pro 2",
        brand="Apple",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=1899,
        rating=4.8,
        description="Reliable ANC earbuds for iPhone users with easy gift appeal.",
        scene_tags=["commute", "daily", "gift"],
        tags=["earphones", "耳机", "降噪", "真无线", "送礼"],
        aliases=["AirPods Pro 2", "苹果降噪耳机"],
        features={
            "battery_hours": 30,
            "noise_cancel_score": 9.0,
            "weight_grams": 48,
            "warranty_years": 1,
        },
        stock=15,
    ),
    _product(
        sku="EAR-HUA-FBP3",
        name="Huawei FreeBuds Pro 3",
        brand="Huawei",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=1499,
        rating=4.6,
        description="Well-rounded ANC earbuds with good call quality and comfort.",
        scene_tags=["commute", "office", "daily"],
        tags=["earphones", "耳机", "降噪", "真无线"],
        aliases=["华为 FreeBuds"],
        features={
            "battery_hours": 31,
            "noise_cancel_score": 8.7,
            "weight_grams": 50,
            "warranty_years": 1,
        },
        stock=11,
    ),
    _product(
        sku="EAR-BOS-QCUE",
        name="Bose QuietComfort Ultra Earbuds",
        brand="Bose",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=1999,
        rating=4.5,
        description="Premium earbuds with strong ANC and comfortable fit for travel.",
        scene_tags=["commute", "travel", "daily"],
        tags=["earphones", "耳机", "降噪", "真无线"],
        aliases=["Bose QC Ultra Earbuds"],
        features={
            "battery_hours": 24,
            "noise_cancel_score": 9.2,
            "weight_grams": 54,
            "warranty_years": 1,
        },
        stock=8,
    ),
    _product(
        sku="EAR-BEA-STUDIOPRO",
        name="Beats Studio Pro",
        brand="Beats",
        category=ProductCategory.earphones,
        subcategory="noise_cancelling_headphones",
        price=2499,
        rating=4.4,
        description="Bass-forward ANC headphone with strong gift recognizability.",
        scene_tags=["commute", "gym", "gift"],
        tags=["earphones", "耳机", "降噪", "头戴式", "送礼"],
        aliases=["Beats 头戴耳机"],
        features={
            "battery_hours": 40,
            "noise_cancel_score": 8.4,
            "weight_grams": 260,
            "warranty_years": 1,
        },
        stock=10,
    ),
    _product(
        sku="EAR-BEA-FITPRO",
        name="Beats Fit Pro",
        brand="Beats",
        category=ProductCategory.earphones,
        subcategory="sport_earbuds",
        price=1599,
        rating=4.3,
        description="Secure-fit earbuds suited for workout and active commute.",
        scene_tags=["gym", "commute", "daily"],
        tags=["earphones", "耳机", "运动", "真无线"],
        aliases=["Beats 运动耳机"],
        features={
            "battery_hours": 24,
            "noise_cancel_score": 8.2,
            "weight_grams": 56,
            "warranty_years": 1,
        },
        stock=14,
    ),
    _product(
        sku="EAR-NTG-EAR2024",
        name="Nothing Ear (2024)",
        brand="Nothing",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=999,
        rating=4.5,
        description="Design-led ANC earbuds that work well for gift scenarios.",
        scene_tags=["gift", "daily", "commute"],
        tags=["earphones", "耳机", "设计感", "颜值", "真无线"],
        aliases=["Nothing 耳机"],
        features={
            "battery_hours": 40,
            "noise_cancel_score": 8.5,
            "weight_grams": 52,
            "warranty_years": 1,
        },
        stock=3,
    ),
    _product(
        sku="EAR-ANK-L4NC",
        name="Soundcore Liberty 4 NC",
        brand="Soundcore",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=699,
        rating=4.4,
        description="Affordable ANC earbuds for value-driven commute shopping.",
        scene_tags=["commute", "daily"],
        tags=["earphones", "耳机", "降噪", "性价比", "真无线"],
        aliases=["声阔耳机"],
        features={
            "battery_hours": 50,
            "noise_cancel_score": 8.3,
            "weight_grams": 60,
            "warranty_years": 1,
        },
        stock=21,
    ),
    _product(
        sku="EAR-JBL-TOURP3",
        name="JBL Tour Pro 3",
        brand="JBL",
        category=ProductCategory.earphones,
        subcategory="true_wireless_anc",
        price=1899,
        rating=4.4,
        description="Feature-rich premium earbuds with a smart case for travel.",
        scene_tags=["travel", "commute", "daily"],
        tags=["earphones", "耳机", "降噪", "真无线"],
        aliases=["JBL Tour"],
        features={
            "battery_hours": 32,
            "noise_cancel_score": 8.8,
            "weight_grams": 58,
            "warranty_years": 1,
        },
        stock=9,
    ),
    _product(
        sku="EAR-SON-LINKFIT",
        name="Sony LinkBuds Fit",
        brand="Sony",
        category=ProductCategory.earphones,
        subcategory="design_earbuds",
        price=1499,
        rating=4.4,
        description="Lightweight stylish earbuds suited to daily commute and gifting.",
        scene_tags=["gift", "commute", "daily"],
        tags=["earphones", "耳机", "设计感", "颜值", "真无线"],
        aliases=["LinkBuds", "索尼送礼耳机"],
        features={
            "battery_hours": 21,
            "noise_cancel_score": 7.9,
            "weight_grams": 40,
            "warranty_years": 1,
        },
        stock=5,
    ),
    _product(
        sku="EAR-MAR-MOTIF2",
        name="Marshall Motif II A.N.C.",
        brand="Marshall",
        category=ProductCategory.earphones,
        subcategory="design_earbuds",
        price=1599,
        rating=4.3,
        description="Retro-styled earbuds with solid ANC and strong design appeal.",
        scene_tags=["gift", "daily", "commute"],
        tags=["earphones", "耳机", "设计感", "颜值", "真无线"],
        aliases=["Marshall 耳机"],
        features={
            "battery_hours": 30,
            "noise_cancel_score": 8.0,
            "weight_grams": 57,
            "warranty_years": 1,
        },
        stock=4,
    ),
)


def get_seed_catalog() -> list[Product]:
    return [product.model_copy(deep=True) for product in _SEED_CATALOG]


def find_product(sku: str, catalog: Sequence[Product] | None = None) -> Product:
    normalized = sku.strip().upper()
    for product in catalog or _SEED_CATALOG:
        if product.sku == normalized:
            return product.model_copy(deep=True)
    raise LookupError(f"Unknown SKU: {sku}")


def seed_counts() -> dict[str, int]:
    counts = {category.value: 0 for category in ProductCategory}
    for product in _SEED_CATALOG:
        counts[product.category.value] += 1
    return counts
